[versions]
agp = "8.13.0"
commonsLogging = "1.2"
kotlin = "2.1.10"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
legacySupportV4 = "1.0.0"
gridlayout = "1.0.0"
preference = "1.2.1"
accompanistSwiperefresh = "0.36.0"
javaxAnnotationApi = "1.3.2"
glanceMaterial = "1.1.1"
glanceAppwidget = "1.1.1"
compose = "1.7.8"
materialVersion = "1.7.8"
javaxServletApi = "4.0.1"
mimedir = "2.1.0"
animationCore = "1.7.8"
commonsLoggingVersion = "1.3.5"
groovy = "3.0.24"
tomcatJuli = "11.0.6"
juli = "6.0.53"
jsoup = "1.21.1"
xstream = "1.4.21"
xmlpull = "1.1.3.4d_b4_min"
materialIconsExtendedAndroid = "1.7.8"
coreI18n = "1.0.0"

[libraries]
commons-logging = { module = "commons-logging:commons-logging", version.ref = "commonsLogging" }
compose-ui = { group = "androidx.compose.ui", name = "ui", version = "1.9.3" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version = "1.9.3" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version = "1.9.3" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version = "1.9.3" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version = "1.9.3" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.9.3" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.11.0" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2025.10.00" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.17.0" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version = "1.2.0-alpha02" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version = "1.2.0-alpha02" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.9.4" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version = "1.3.0" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.7.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
material = { group = "com.google.android.material", name = "material", version = "1.13.0" }
androidx-activity = { group = "androidx.activity", name = "activity", version = "1.11.0" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.2.1" }
androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version = "1.1.0" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version = "2.9.4" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.9.4" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version = "2.9.5" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version = "2.9.5" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version = "1.8.9" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version = "1.4.0" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version = "2.9.5" }
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
skrapeit = { group = "it.skrape", name = "skrapeit", version = "1.2.2" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.1" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version = "2.10.5" }
accompanist-swiperefresh = { group = "com.google.accompanist", name = "accompanist-swiperefresh", version.ref = "accompanistSwiperefresh" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version = "1.9.1" }
javax-annotation-api = { group = "javax.annotation", name = "javax.annotation-api", version.ref = "javaxAnnotationApi" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.9.0" }
androidx-glance-material = { group = "androidx.glance", name = "glance-material", version.ref = "glanceMaterial" }
androidx-glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glanceAppwidget" }
androidx-material = { group = "androidx.compose.material", name = "material", version = "1.9.3" }
javax-servlet-api = { group = "javax.servlet", name = "javax.servlet-api", version.ref = "javaxServletApi" }
mimedir = { group = "org.ietf", name = "mimedir", version.ref = "mimedir" }
androidx-animation-core = { group = "androidx.compose.animation", name = "animation-core", version.ref = "animationCore" }
commons-logging-commons-logging = { group = "commons-logging", name = "commons-logging", version.ref = "commonsLoggingVersion" }
groovy = { group = "org.codehaus.groovy", name = "groovy", version = "3.0.25" }
tomcat-juli = { group = "org.apache.tomcat", name = "tomcat-juli", version.ref = "tomcatJuli" }
juli = { group = "org.apache.tomcat", name = "juli", version.ref = "juli" }
jsoup = { group = "org.jsoup", name = "jsoup", version = "1.21.2" }
xstream = { group = "com.thoughtworks.xstream", name = "xstream", version.ref = "xstream" }
xmlpull = { group = "xmlpull", name = "xmlpull", version.ref = "xmlpull" }
androidx-compose-material-icons-extended-android = { group = "androidx.compose.material", name = "material-icons-extended-android", version.ref = "materialIconsExtendedAndroid" }
androidx-core-i18n = { group = "androidx.core", name = "core-i18n", version.ref = "coreI18n" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

